"""Add pgvector embedding to entity

Revision ID: b799df95df0c
Revises: cf4e11a99c07
Create Date: 2026-08-16 11:45:51.421602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'b799df95df0c'
down_revision: Union[str, Sequence[str], None] = 'cf4e11a99c07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'embedding')
    # ### end Alembic commands ###
